name: Ethernaut Slack Bot
on:
  schedule:
    - cron: "0 * * * *"
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'         
    - run: npm ci  
    - run: npm start
      env:
        ETHERNAUT_ADDRESS: ${{ secrets.ETHERNAUT_ADDRESS }}
        NETWORK_PROVIDER_URL: ${{ secrets.NETWORK_PROVIDER_URL }}
        SLACK_BOT_CHANNEL: ${{ secrets.SLACK_BOT_CHANNEL }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_BOT_USERGROUP_ID: ${{ secrets.SLACK_BOT_USERGROUP_ID }}
        SLACK_BOT_WALLET_FIELD_ID: ${{ secrets.SLACK_BOT_WALLET_FIELD_ID }}
        SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}        
